"""Shared versioning core for working-file history workflows."""

from .model import (
    BackupResult,
    VersionOwner,
    VersionRecord,
    VersionSnapshotMember,
    VersionStreamSpec,
    stream_filename,
    stream_key_for,
)
from .service import list_version_records, promote_version, save_version
from .store import (
    DEFAULT_MANIFEST_FILENAME,
    MANIFEST_SCHEMA_VERSION,
    backup_file,
    backup_if_changed,
    build_manifest,
    bundle_dirname,
    compute_signature,
    current_record,
    get_manifest_path,
    history_as_records,
    list_bundle_versions,
    list_versions,
    load_manifest,
    next_bundle_version,
    next_version,
    record_publish,
    save_manifest,
    version_label,
    versioned_filename,
)
from .stream_paths import path_matches_stream, stream_dirname

__all__ = [
    "BackupResult",
    "DEFAULT_MANIFEST_FILENAME",
    "MANIFEST_SCHEMA_VERSION",
    "VersionOwner",
    "VersionRecord",
    "VersionSnapshotMember",
    "VersionStreamSpec",
    "backup_file",
    "backup_if_changed",
    "bundle_dirname",
    "build_manifest",
    "compute_signature",
    "current_record",
    "get_manifest_path",
    "history_as_records",
    "list_bundle_versions",
    "list_version_records",
    "list_versions",
    "load_manifest",
    "next_bundle_version",
    "path_matches_stream",
    "next_version",
    "promote_version",
    "record_publish",
    "save_version",
    "save_manifest",
    "stream_filename",
    "stream_dirname",
    "stream_key_for",
    "version_label",
    "versioned_filename",
]
